services:
  postgres-n8n:
    image: postgres:15
    container_name: postgres-n8n
    environment:
      POSTGRES_DB: ${N8N_DB_NAME}
      POSTGRES_USER: ${N8N_DB_USER}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
    volumes:
      - ./postgres_n8n_data:/var/lib/postgresql/data
    networks:
      - n8n_network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:1.15.1
    container_name: n8n-app
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${N8N_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres-n8n
    networks:
      - n8n_network
    restart: unless-stopped

volumes:
  postgres_n8n_data:
  n8n_data:

networks:
  n8n_network:
    driver: bridge